### ISSUE TITLE
Not complete

### ISSUE THREAD

**Issue by allanitis** [ulfsa/tink-openapi#1]
Hey did this ever get finished? Would love to see if it was.

**Comment by s2crm** [comment]
Hi there, sadly no due to time constraints. However it seems Tink actually has a Swagger specification used internally, but has chosen to not publish it. Maybe nagging to publish (at least parts of it) will do the trick.

**Comment by ulfsa** [comment]
Hi there, sadly no due to time constraints. However it seems Tink actually has a Swagger specification used internally, but has chosen to not publish it. Maybe nagging to publish (at least parts of it) will do the trick.
